[package]
name = "wthr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.50"
reqwest = "0.12.24"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
